export const courseCardData = [
  {
    id: 1,
    title: "Complete Web Development",
    teacherName: "Sumit Shaha",
    price: 500,
    stars: 3,
    reviews: 5,
    lessons: 10,
    students: 100,
    bookmarked: false,
  },
  {
    id: 2,
    title: "Complete Web Development",
    teacherName: "Sumit Shaha",
    price: 500,
    stars: 3,
    reviews: 5,
    lessons: 10,
    students: 100,
    bookmarked: false,
  },
  {
    id: 3,
    title: "Complete Web Development",
    teacherName: "Sumit Shaha",
    price: 500,
    stars: 3,
    reviews: 5,
    lessons: 10,
    students: 100,
    bookmarked: false,
  },
  {
    id: 4,
    title: "Complete Web Development",
    teacherName: "Sumit Shaha",
    price: 500,
    stars: 3,
    reviews: 5,
    lessons: 10,
    students: 100,
    bookmarked: false,
  },
  {
    id: 5,
    title: "Complete Web Development",
    teacherName: "Sumit Shaha",
    price: 500,
    stars: 3,
    reviews: 5,
    lessons: 10,
    students: 100,
    bookmarked: false,
  },

  //   {
  //     id: 6,
  //     title: "Complete Web Development",
  //     teacherName: "Sumit Shaha",
  //     courseImage:
  //       "https://img.freepik.com/free-vector/programming-concept-illustration_114360-1213.jpg?w=740&t=st=1701097379~exp=1701097979~hmac=0cb7d55c2a63a833c897f577c6e0a535be5eb140bec9caa5d5590a5cd4b87d69",
  //     teacherImage: "https://img-b.udemycdn.com/user/200_H/31334738_a13c_3.jpg",
  //     price: 500,
  //     stars: 3,
  //     reviews: 5,
  //     lessons: 10,
  //     students: 100,
  //     bookmarked: false,
  //   },
];
